spring:
  application:
    name: 'T Bike API'

  #******************** connection config ********************#
  datasource:
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
    url: 'jdbc:mysql://localhost:3306/t_bike?createDatabaseIfNotExist=true&charset=utf8'
    username: 'root'
    password: '12345678'

  #******************** jpa config ********************#
  jpa:
    #database-platform: 'org.hibernate.dialect.MySQLDialect'

    #******************** naming config ********************#
    hibernate:
      naming:
        implicit-strategy: 'org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy'
        physical-strategy: 'org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl'

    #******************** debug config ********************#
    show-sql: true
    open-in-view: false

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        type: TRACE

########################## CUSTOMIZE ###########################

file-storage:
  resources-base: true
  root: 'files'
  directories:
    images: 'images'
    videos: 'videos'

application:
  security:
    jwt:
      secret-key: afe037d4197e043959f6ac4dde6c0ffa00e27a8837af537a16facb4b625b9991
      expiration: 86400000 # a day
