insert into brands (id, name, image_url, description, deleted)
values (1, 'Black Line', 'http://localhost:8080/api/images/YnJhMQ.jpg', '', false),
       (2, 'Funky', 'http://localhost:8080/api/images/YnJhMg.jpg', '', false),
       (3, 'Hector', 'http://localhost:8080/api/images/YnJhMw.jpg', '', false),
       (4, 'Janier', 'http://localhost:8080/api/images/YnJhNA.jpg', '', false),
       (5, 'Kurashi', 'http://localhost:8080/api/images/YnJhNQ.jpg', '', false),
       (6, 'Lanq', 'http://localhost:8080/api/images/YnJhNg.jpg', '', false),
       (7, 'Melody', 'http://localhost:8080/api/images/YnJhNw.jpg', '', false),
       (8, 'Nesto', 'http://localhost:8080/api/images/WW5KaE9B.jpg', '', false),
       (9, 'Royall Baby', 'http://localhost:8080/api/images/YnJhOQ.jpg', '', false),
       (10, 'Satako', 'http://localhost:8080/api/images/YnJhMTA.jpg', '', false),
       (11, 'Skukyo', 'http://localhost:8080/api/images/YnJhMTE.jpg', '', false),
       (12, 'TrinX', 'http://localhost:8080/api/images/YnJhMTI.jpg', '', false),
       (13, 'Brave Will', 'http://localhost:8080/api/images/YnJhMTM.jpg', '', false),
       (14, 'Jsxiong', 'http://localhost:8080/api/images/YnJhMTQ.jpg', '', false),
       (15, 'Fornix', 'http://localhost:8080/api/images/YnJhMTU.jpg', '', false),
       (16, 'Papylus', 'http://localhost:8080/api/images/YnJhMTY.jpg', '', false),
       (17, 'Califa', 'http://localhost:8080/api/images/YnJhMTc.jpg', '', false),
       (18, 'Life', 'http://localhost:8080/api/images/YnJhMTg.jpg', '', false),
       (19, 'Catani', 'http://localhost:8080/api/images/YnJhMTk.jpg', '', false),
       (20, 'Vicky', 'http://localhost:8080/api/images/YnJhMjA.jpg', '', false);