insert into products (id,
                      sku,
                      brand_id,
                      category_id,
                      name,
                      size,
                      frame,
                      saddle,
                      seat_post,
                      bell,
                      fork,
                      shock,
                      handlebar,
                      handlebar_stem,
                      pedal,
                      crankset,
                      bottom_bracket,
                      chain,
                      chain_guard,
                      cassette,
                      front_derailleur,
                      rear_derailleur,
                      rims,
                      hubs,
                      spokes,
                      tires,
                      valve,
                      brakes,
                      brake_levers)
values (1,
        'Rs900',
        1,
        3,
        'Xe Đạp Địa Hình MTB Black Line RS900',
        '27.5 inch',
        'Hợp kim nhôm, dây âm sườn',
        '',
        'Hợp kim nhôm Black line',
        '',
        'Hợp kim thép Black line, phuộc lò xo, có khóa hành trình',
        '',
        'Hợp kim thép',
        'Hợp kim nhôm Black line',
        '',
        'Hợp kim nhôm EMMELLE',
        '',
        'Taya',
        '',
        '',
        'Shimano Tourney',
        'Shimano Tourney',
        'Hợp kim nhôm',
        '',
        '',
        'CST 27.5x1.95',
        '',
        'Hợp kim nhôm Black line',
        ''),
       (2,
        'Fixcong04',
        2,
        2,
        'Xe Đạp Fixed Gear Funky Popping Nhật Bản',
        'S',
        'Hợp kim nhôm',
        '',
        'Hợp kim nhôm FUNKY',
        '',
        'Hợp kim nhôm',
        '',
        'Hợp kim nhôm',
        'Hợp kim nhôm',
        '',
        'Hợp kim nhôm FUNKY LOOSE, Cốt rỗng, Bạc đạn',
        '',
        'FNC',
        '',
        '',
        '',
        '',
        'Hợp kim nhôm 2 lớp',
        '',
        '',
        'Kenda 700x25C',
        '',
        'Thắng gôm',
        ''),
       (3,
        '',
        2,
        2,
        'Xe Đạp Fixed Gear Funky Locking Nhật Bản Giá Rẻ',
        'M, L',
        '',
        '',
        '',
        '',
        'Hợp kim nhôm',
        '',
        '',
        '',
        '',
        'Hợp kim nhôm Funky, Cốt rỗng, Bạc đạn',
        '',
        '',
        '',
        '',
        '',
        '',
        'Hợp kim nhôm 2 lớp, cao 4cm',
        '',
        '',
        'KENDA 700x25C',
        '',
        '',
        ''),
       (4,
        '18S1',
        11,
        1,
        'Xe Đạp Trẻ Em Bé Gái Shukyo S1',
        '18 Inch',
        'Hợp kim thép',
        'Mút bọc da mềm lò xo giảm sóc',
        'Thép',
        '',
        'Hợp kim thép',
        '',
        'Hợp kim thép',
        'Thép',
        '',
        'Thép bạc đạn',
        '',
        '',
        '',
        'Líp đơn 16T',
        '',
        '',
        'Nhôm 1 lớp',
        '',
        '',
        'Classic 18x21.25',
        '',
        'Phanh gôm, Phanh đùm',
        ''),
       (5,
        'TX100',
        18,
        4,
        'Xe Đạp Touring Life TX100',
        '',
        'Hợp kim nhôm không mối hàn',
        'LIFE',
        'Hợp kim nhôm LIFE',
        '',
        'Hợp kim thép',
        '',
        'Hợp kim nhôm',
        '',
        'Hợp kim nhôm',
        '',
        'Hợp kim nhôm PROWHEEL',
        '',
        'KMC',
        '',
        'Líp vặn SHIMANO TZ500',
        'SHIMANO Tourney TZ-510',
        'SHIMANO Tourney TZ-510',
        'Hợp kim nhôm 2 lớp, cao 3cm',
        '',
        'KENDA 700x28C',
        '',
        'Phanh đĩa cơ',
        ''),
       (6,
        'pr700s',
        16,
        5,
        'Xe Đạp Đua Papylus PR700s',
        '46',
        'Hợp kim Nhôm không mối hàn, dây âm sườn',
        'PAPYLUS',
        'Hợp kim Nhôm PAPYLUS',
        '',
        'Hợp kim thép',
        '',
        'PAPYLUS - Hợp kim thép',
        'PAPYLUS, Hợp kim Nhôm',
        '',
        'Hợp kim nhôm PAPYLUS, Cốt vuông, Bạc đạn',
        '',
        'TEC 7 Tốc độ',
        '',
        'Líp vặn ATA 7 tầng',
        'SHIMANO TZ500',
        'SHIMANO TZ500',
        'Hợp kim nhôm PAPYLUS 2 lớp, cao 4cm',
        '',
        '',
        'COMPASS 700x28C',
        '',
        'Phanh đĩa cơ DUODER',
        ''),
       (7,
        'Ca-6.2',
        19,
        5,
        'Xe Đạp Đua Catani CA-6.2',
        '48',
        'Hợp kim nhôm đúc',
        'Nệm Yên Da',
        'Nhôm',
        '',
        'Hợp kim nhôm đúc',
        '',
        'Hợp kim nhôm',
        'Nhôm',
        '',
        'Trục rỗng bạc đạn',
        '',
        'TechPower',
        '',
        'Thả ATA 8s cối nổ',
        'Shimano Clarís',
        'Shimano Clarís',
        'Nhôm hai lớp 4cm',
        '',
        '',
        'Kenda 700x32',
        '',
        'Phanh đĩa cơ Shimano TourneyTX',
        ''),
       (8,
        '24G17',
        15,
        6,
        'Xe Đạp Nữ Swat SW24B',
        '24 Inch',
        'Hợp kim thép',
        '',
        '',
        '',
        'Hợp kim thép',
        '',
        'Hợp kim thép',
        'Hợp kim nhôm',
        '',
        'Hợp kim thép, Bi bạc đạn',
        '',
        '',
        '',
        '',
        '',
        '',
        'Hợp kim nhôm',
        '',
        '',
        '24x 1 3/8',
        '',
        'Phanh gôm, Phanh đùm',
        ''),
       (9,
        'Misa',
        17,
        6,
        'Xe Đạp Nữ Califa Misa',
        '26 Inch',
        'Hợp Kim Thép',
        'Nệm Yên Da',
        'Thép',
        '',
        'Thép',
        '',
        'Thép',
        'Thép',
        '',
        'Thép cốt vuông bạc đạn',
        '',
        'FFCZ51',
        '',
        'Líp Vặn 7S',
        'Tay đề vặn shimano REVOSHIFT',
        'SHIMANO TY 21B',
        'Nhôm 1 lớp',
        '',
        '',
        'CST 26x1 3/8',
        '',
        'Phanh đĩa cơ',
        ''),
       (10,
        '20T33',
        14,
        1,
        'Xe Đạp Cho Bé Trai Jsxiong 2301',
        '20 Inch',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        'Hợp kim nhôm',
        '',
        '',
        '20x2.125',
        '',
        'Phanh gôm, phanh đùm',
        ''),
       (11,
        '18T36',
        7,
        1,
        'Xe Đạp Trẻ Em Bé Trai Melody',
        '18 Inch',
        'Hợp kim thép',
        '',
        'Hợp kim thép',
        '',
        'Hợp kim thép',
        '',
        'Hợp kim thép',
        'Hợp kim thép',
        '',
        'Hợp kim thép, Bi côn',
        '',
        '',
        '',
        '',
        '',
        '',
        'Hợp kim nhôm',
        '',
        '',
        '18x2.125',
        '',
        'Phanh gôm, Phanh đùm',
        ''),
       (12,
        '26g12',
        13,
        6,
        'Xe Đạp Nữ Brave Will Nữ Q1',
        '26 inch',
        'Hợp kim nhôm',
        '',
        'Hợp kim nhôm',
        '',
        'Hợp kim thép',
        '',
        'Hợp kim nhôm',
        'Hợp kim nhôm',
        '',
        'Hợp kim nhôm, Cốt vuông, Bi bạc đạn',
        '',
        'MAYA 7 tốc độ',
        '',
        'Líp vặn Sunrun 7 tầng',
        'Tay đề vặn Shimano Revoshift (1 đĩa, 7 líp)',
        'Shimano Tourney Tz',
        'Hợp kim nhôm',
        '',
        '',
        'KENDA 26x1.5',
        '',
        'Phanh gôm',
        ''),
       (13,
        'Pr900',
        16,
        5,
        'Xe Đạp Đua Paylus PR900',
        '',
        'Nhôm 6061 khí động học siêu nhẹ, không mối hàn, cáp âm khung. Sơn tĩnh điện 3 lớp cao cấp',
        'Mút bọc da mềm',
        'Hợp kim nhôm',
        '',
        'Càng bản dẹp không mối hàn',
        '',
        'Hợp kim nhôm',
        'Hợp kim nhôm',
        '',
        'PAPYLUS - Nhôm Trục rỗng 50/34T, cốt BB cao cấp',
        '',
        'TAYA 9s - Thép rỗng siêu nhẹ',
        '',
        'SAIGUAN 9s - Líp thả 11/32T',
        'L-TWOO R5',
        'L-TWOO R5',
        'PAPYLUS - Nhôm 2 lớp, vành chém gió cao 60mm',
        '',
        '',
        'CHAOYANG 700x28C',
        '',
        'Phanh đĩa cơ',
        ''),
       (14,
        'Vc800',
        20,
        2,
        'Xe Đạp Địa Hình MTB Vicky Crazy VC800',
        '26 Inch',
        'Hợp kim thép',
        'VICKY',
        'Hợp kim thép Vicky',
        '',
        'Hợp kim thép, giảm xóc lò xo',
        '',
        'Hợp kim thép',
        'Hợp kim nhôm',
        '',
        '1 tầng',
        '',
        'DTO',
        '',
        '',
        '',
        '',
        'Hợp kim nhôm',
        '',
        '',
        'WANDA 26X2.125',
        '',
        'Hợp kim nhôm',
        ''),
       (15,
        'V1000',
        5,
        3,
        'Xe Đạp Địa Hình MTB TrinX V1000 Pro',
        '29 Inch',
        'Carbon T800',
        'Nệm Yên da TrinX',
        'Nhôm Magix',
        '',
        'Phuộc hơi hợp kim nhôm',
        '',
        'Nhôm',
        'Nhôm',
        '',
        'Nhôm trục rỗng 34T',
        '',
        'KMC',
        '',
        'Líp Thả Sugek 12s cối nổ',
        'Shimano SLX 7100',
        'Shimano SLX 7100',
        'Nhôm hai lớp 2cm',
        '',
        '',
        'MAXXIS 29x2.20',
        '',
        'Thắng đĩa dầu Shimano MT200',
        ''),
       (16,
        'Tr218',
        5,
        3,
        'Xe Đạp Địa Hình MTB TrinX TR218',
        '27.5 Inch',
        'Nhôm',
        'Nệm Yên da',
        'Nhôm',
        '',
        'Thép lò xo có lock',
        '',
        'Thép',
        'Nhôm',
        '',
        'Thép cốt vuông bạc đạn',
        '',
        'MAYA',
        '',
        'Líp vặn Shimano 7s',
        'Shimano Tourney TZ',
        'Shimano Tourney TZ',
        'Nhôm hai lớp 2cm',
        '',
        '',
        'CST 27.5x2.10',
        '',
        'Thắng đĩa cơ',
        ''),
       (17,
        'CA-6.3',
        13,
        4,
        'Xe Đạp Touring Catani CA-6.3',
        '48',
        'Hợp kim nhôm đúc',
        'Nệm Yên Da',
        'Nhôm',
        'Hợp kim nhôm đúc',
        '',
        'Hợp kim nhôm',
        'Nhôm',
        '',
        'Shimano Nhôm cốt vuông bạc đạn',
        '',
        'TechPower',
        '',
        '',
        'Thả ATA 8s cối nổ',
        'Shimano Tourney',
        'Shimano Altus',
        'Nhôm hai lớp 4cm',
        '',
        '',
        'Kenda 700x32',
        '',
        'Phanh đĩa dầu Shimano MT200',
        ''),
       (18,
        'CA-PRO',
        13,
        4,
        'Xe Đạp Touring Catani Ca-Pro 700c',
        '',
        'Hợp kim nhôm, Không mối hàn, Dây âm sườn',
        '',
        'Hợp kim nhôm',
        '',
        'Hợp kim thép',
        '',
        'Hợp kim thép',
        'Hợp kim nhôm',
        '',
        'Hợp kim nhôm Prowheel, Cốt vuông, Bạc đạn',
        '',
        'PRW 7 tốc độ',
        '',
        'Líp vặn Shimano MF-TZ500 7 tầng',
        'Shimano Tourney Tz',
        'Shimano Tourney Tz',
        'Hợp kim nhôm',
        '',
        '',
        'KENDA 700x32',
        '',
        'Phanh đĩa cơ',
        '');
