INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (1, true, 'Đen đỏ', 'http://localhost:8080/api/images/mtb-fascino-fs-126-den-do-1-org.jpg', 5990000, 100, 1);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (2, false, 'Đỏ', 'http://localhost:8080/api/images/mtb-fascino-fs-126-den-do-1-org.jpg', 5990000, 105, 1);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (3, false, 'Xám', 'http://localhost:8080/api/images/mtb-fascino-fs-126-den-do-1-org.jpg', 4990000, 100, 1);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (4, false, 'Xám đen', 'http://localhost:8080/api/images/mtb-fascino-fs-126-den-do-1-org.jpg', 4990000, 97, 1);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (5, false, 'Xanh dương', 'http://localhost:8080/api/images/mtb-fascino-fs-126-den-do-1-org.jpg', 4990000, 100, 1);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (6, true, 'Đỏ', 'http://localhost:8080/api/images/Untitled-1-01-1.png', 8090000, 100, 2);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (7, false, 'Ghi', 'http://localhost:8080/api/images/Untitled-1-01-1.png', 7090000, 100, 2);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (8, false, 'Trắng', 'http://localhost:8080/api/images/Untitled-1-01-1.png', 6090000, 100, 2);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (9, false, 'Vàng đồng', 'http://localhost:8080/api/images/Untitled-1-01-1.png', 6090000, 100, 2);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (10, true, 'Đen', 'http://localhost:8080/api/images/jumper-green-edited.png', 8590000, 103, 3);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (11, false, 'Trắng', 'http://localhost:8080/api/images/jumper-green-edited.png', 8590000, 100, 3);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (12, false, 'Bạc', 'http://localhost:8080/api/images/jumper-green-edited.png', 7590000, 100, 3);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (13, false, 'Rêu', 'http://localhost:8080/api/images/jumper-green-edited.png', 7590000, 100, 3);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (14, false, 'Xanh', 'http://localhost:8080/api/images/jumper-green-edited.png', 7590000, 100, 3);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (15, true, 'Hồng', 'http://localhost:8080/api/images/xdtn-ld2401.webp', 1362000, 100, 4);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (16, false, 'Tím', 'http://localhost:8080/api/images/xdtn-ld2401.webp', 1290000, 100, 4);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (17, false, 'Kem', 'http://localhost:8080/api/images/xdtn-ld2401.webp', 1290000, 100, 4);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (18, true, 'Ghi', 'http://localhost:8080/api/images/jumper-red-edited.png', 5600000, 100, 5);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (19, false, 'Bạc', 'http://localhost:8080/api/images/jumper-red-edited.png', 6000000, 100, 5);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (20, false, 'Trắng', 'http://localhost:8080/api/images/jumper-red-edited.png', 5000000, 100, 5);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (21, false, 'Xanh dương', 'http://localhost:8080/api/images/jumper-red-edited.png', 4990000, 100, 5);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (22, false, 'Xanh rêu', 'http://localhost:8080/api/images/jumper-red-edited.png', 6000000, 100, 5);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (23, true, 'Đen đỏ', 'http://localhost:8080/api/images/mtb-fascino-fs-126-den-do-1-org.jpg', 3890000, 100, 6);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (24, false, 'Trắng đỏ', 'http://localhost:8080/api/images/mtb-fascino-fs-126-den-do-1-org.jpg', 3890000, 100, 6);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (25, false, 'Xanh ghi', 'http://localhost:8080/api/images/mtb-fascino-fs-126-den-do-1-org.jpg', 4990000, 100, 6);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (26, false, 'Xanh rêu vàng', 'http://localhost:8080/api/images/mtb-fascino-fs-126-den-do-1-org.jpg', 5315520, 100, 6);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (27, false, 'Ghi cam', 'http://localhost:8080/api/images/mtb-fascino-fs-126-den-do-1-org.jpg', 5315520, 100, 6);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (28, true, 'Đen', 'http://localhost:8080/api/images/jumper-green-edited.png', 8290000, 100, 7);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (29, false, 'Ghi', 'http://localhost:8080/api/images/jumper-green-edited.png', 8290000, 100, 7);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (30, false, 'Kem', 'http://localhost:8080/api/images/jumper-green-edited.png', 8290000, 97, 7);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (31, false, 'Trắng', 'http://localhost:8080/api/images/jumper-green-edited.png', 8290000, 100, 7);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (32, false, 'Trắng đổi màu', 'http://localhost:8080/api/images/jumper-green-edited.png', 9775000, 100, 7);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (33, false, 'Xanh', 'http://localhost:8080/api/images/jumper-green-edited.png', 9775000, 100, 7);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (34, true, 'Hồng', 'http://localhost:8080/api/images/xdtn-ld2401-tim.webp', 3000000, 100, 8);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (35, false, 'Xanh ngọc', 'http://localhost:8080/api/images/xdtn-ld2401-tim.webp', 2790000, 100, 8);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (36, true, 'Đen', 'http://localhost:8080/api/images/xdtn-ld2401.webp', 3090000, 100, 9);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (37, false, 'Trắng', 'http://localhost:8080/api/images/xdtn-ld2401.webp', 3540000, 100, 9);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (38, false, 'Vàng', 'http://localhost:8080/api/images/xdtn-ld2401.webp', 3090000, 100, 9);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (39, false, 'Xanh', 'http://localhost:8080/api/images/xdtn-ld2401.webp', 3090000, 100, 9);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (40, true, 'Đỏ', 'http://localhost:8080/api/images/08832.webp', 1650000, 100, 10);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (41, false, 'Xám', 'http://localhost:8080/api/images/08832.webp', 1650000, 100, 10);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (42, false, 'Xanh', 'http://localhost:8080/api/images/08832.webp', 1650000, 100, 10);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (43, true, 'Đỏ', 'http://localhost:8080/api/images/08832hong.webp', 1990000, 100, 11);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (44, false, 'Lá', 'http://localhost:8080/api/images/08832hong.webp', 1590000, 100, 11);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (45, false, 'Xanh', 'http://localhost:8080/api/images/08832hong.webp', 1990000, 100, 11);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (46, true, 'Trắng', 'http://localhost:8080/api/images/08832hong.webp', 4790000, 100, 12);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (47, false, 'Vàng kem', 'http://localhost:8080/api/images/08832hong.webp', 5090000, 100, 12);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (48, true, 'Đỏ xanh', 'http://localhost:8080/api/images/Bora1-XanhduongVang.jpg', 8590000, 100, 13);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (49, false, 'Ghi', 'http://localhost:8080/api/images/Bora1-XanhduongVang.jpg', 8590000, 100, 13);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (50, false, 'Ghi đen', 'http://localhost:8080/api/images/Bora1-XanhduongVang.jpg', 9990000, 100, 13);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (51, false, 'Ghi đỏ', 'http://localhost:8080/api/images/Bora1-XanhduongVang.jpg', 9990000, 100, 13);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (52, false, 'Xanh cà phê', 'http://localhost:8080/api/images/Bora1-XanhduongVang.jpg', 8590000, 100, 13);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (53, true, 'Đen đỏ', 'http://localhost:8080/api/images/Vm0wd2QyUXlWa1pOVldScFVtMVNjRlZ0TVZOV1ZteHpWV3hK.jpg', 2530000, 100, 14);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (54, false, 'Đen xanh', 'http://localhost:8080/api/images/Vm0weE1GbFhSWGxTYlRR.jpg', 3000000, 100, 14);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (55, false, 'Ghi cam', 'http://localhost:8080/api/images/download.jpg', 2530000, 100, 14);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (56, false, 'Trắng đỏ', 'http://localhost:8080/api/images/download.jpg', 3000000, 100, 14);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (57, false, 'Trắng xanh', 'http://localhost:8080/api/images/download.jpg', 3000000, 100, 14);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (58, false, 'Xanh vàng', 'http://localhost:8080/api/images/download.jpg', 2530000, 100, 14);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (59, true, 'Đen đỏ', 'http://localhost:8080/api/images/mtb-fascino-fs-126-den-do-1-org.jpg', 18990000, 100, 15);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (60, false, 'Đen xanh', 'http://localhost:8080/api/images/mtb-fascino-fs-126-den-do-1-org.jpg', 21838500, 100, 15);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (61, false, 'Xanh đỏ', 'http://localhost:8080/api/images/mtb-fascino-fs-126-den-do-1-org.jpg', 18990000, 100, 15);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (62, true, 'Trắng', 'http://localhost:8080/api/images/mtb-fascino-fs-126-den-do-1-org.jpg', 5090000, 100, 16);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (63, false, 'Vàng đen', 'http://localhost:8080/api/images/mtb-fascino-fs-126-den-do-1-org.jpg', 5853500, 100, 16);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (64, false, 'Xanh', 'http://localhost:8080/api/images/mtb-fascino-fs-126-den-do-1-org.jpg', 5853500, 100, 16);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (65, false, 'Đen đỏ', 'http://localhost:8080/api/images/mtb-fascino-fs-126-den-do-1-org.jpg', 5090000, 100, 16);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (66, true, 'Đen', 'http://localhost:8080/api/images/download.jpg', 6690000, 100, 17);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (67, false, 'Ghi', 'http://localhost:8080/api/images/download.jpg', 6690000, 100, 17);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (68, false, 'Kem', 'http://localhost:8080/api/images/download.jpg', 7690000, 100, 17);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (69, false, 'Trắng', 'http://localhost:8080/api/images/download.jpg', 7690000, 100, 17);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (70, false, 'Trắng đổi màu', 'http://localhost:8080/api/images/download.jpg', 7690000, 98, 17);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (71, false, 'Xanh', 'http://localhost:8080/api/images/download.jpg', 6690000, 100, 17);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (72, true, 'Bạc', 'http://localhost:8080/api/images/jumper-red-edited.png', 4890000, 100, 18);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (73, false, 'Đen', 'http://localhost:8080/api/images/jumper-red-edited.png', 4890000, 100, 18);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (74, false, 'Đổi màu', 'http://localhost:8080/api/images/jumper-red-edited.png', 5000000, 100, 18);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (75, false, 'Ghi', 'http://localhost:8080/api/images/jumper-red-edited.png', 4890000, 100, 18);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (76, false, 'Trắng', 'http://localhost:8080/api/images/jumper-red-edited.png', 5000000, 100, 18);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (77, false, 'Xanh dương', 'http://localhost:8080/api/images/jumper-red-edited.png', 5000000, 100, 18);
INSERT INTO t_bike.attributes (id, represent, color, image_url, price, quantity, product_id) VALUES (78, false, 'Xanh nhạt', 'http://localhost:8080/api/images/jumper-red-edited.png', 4890000, 100, 18);
